// One-off image optimization pass.
//
// What it does:
//   1. For each JPEG/PNG under public/images/, re-encodes in place at a
//      sensible max dimension + quality. Keeps the same filename + extension.
//   2. Emits a blur-placeholder manifest at src/data/imageBlur.ts that maps
//      each public path to a tiny base64 data URL. The <Image> components
//      read from this manifest at build time so `placeholder="blur"` works
//      on string-src images (which Next can't auto-blur).
//
// Re-run safely: overwrites in place. Stripped EXIF on the way out.
//
// Tuning:
//   - MAX_EDGE 2400 is enough for retina at any container we use (largest
//     is the hero headshot, displayed up to 384px -> 768 physical -> plenty
//     of headroom). Keeps srcset generation healthy at Next image widths.
//   - QUALITY 82 is the standard sweet spot. Visible artifacts start ~75.
//   - PNG: the ACP eagle + logos stay PNG because they use transparency.
//     Quantized to palette; typically 60-85% size reduction.
//   - Skips SVG, PDF, icons, favicons, wordmarks, and anything <100KB
//     (already small enough that re-encoding would risk making it worse).

import { readdir, stat, readFile, writeFile } from "node:fs/promises";
import { join, extname, basename } from "node:path";
import sharp from "sharp";

const ROOT = "public/images";
const MAX_EDGE = 2400;
const QUALITY = 82;
const SKIP_NAMES = new Set([
  "favicon_180x180.png",
  "favicon_512x512.png",
  "donate-qr.png",
  "writein-cuteri-wordmark.svg",
  "sc01-district-map.svg",
  // PDFs handled by extension filter below
]);
const MIN_SIZE_BYTES = 100 * 1024; // skip anything already <100KB

const BLUR_WIDTH = 16; // tiny preview width for placeholder

/** @type {Record<string, string>} */
const blurManifest = {};

async function processFile(path) {
  const name = basename(path);
  const ext = extname(path).toLowerCase();
  if (SKIP_NAMES.has(name)) return { path, skipped: "skip-list" };
  if (ext === ".svg" || ext === ".pdf") return { path, skipped: "vector/pdf" };

  const beforeStat = await stat(path);
  const beforeBytes = beforeStat.size;

  const input = await readFile(path);
  const image = sharp(input, { failOn: "none" }).rotate(); // honor EXIF orientation, then strip
  const meta = await image.metadata();

  // Resize only if larger than MAX_EDGE on the long side
  const longEdge = Math.max(meta.width ?? 0, meta.height ?? 0);
  const pipeline = longEdge > MAX_EDGE ? image.resize({ width: meta.width >= meta.height ? MAX_EDGE : undefined, height: meta.height > meta.width ? MAX_EDGE : undefined, withoutEnlargement: true }) : image;

  let outBuffer;
  if (ext === ".jpg" || ext === ".jpeg") {
    outBuffer = await pipeline
      .jpeg({ quality: QUALITY, mozjpeg: true, progressive: true })
      .toBuffer();
  } else if (ext === ".png") {
    // If source is large and opaque we could switch to JPEG, but we keep PNG
    // to avoid breaking transparency for logos.
    outBuffer = await pipeline
      .png({ compressionLevel: 9, palette: true })
      .toBuffer();
  } else {
    return { path, skipped: `unsupported ext ${ext}` };
  }

  const afterBytes = outBuffer.length;

  // Only write if the new file is meaningfully smaller (>=10%). Otherwise
  // the source was already well-optimized and we'd just churn the file.
  if (afterBytes >= beforeBytes * 0.9 && beforeBytes < MIN_SIZE_BYTES) {
    // Still generate blur for manifest
  } else if (afterBytes < beforeBytes) {
    await writeFile(path, outBuffer);
  }

  // Blur placeholder
  const blur = await sharp(outBuffer)
    .resize({ width: BLUR_WIDTH })
    .jpeg({ quality: 40 })
    .toBuffer();
  const publicPath = "/" + path.replace(/^public\//, "");
  blurManifest[publicPath] = `data:image/jpeg;base64,${blur.toString("base64")}`;

  return {
    path,
    beforeKB: Math.round(beforeBytes / 1024),
    afterKB: Math.round(afterBytes / 1024),
    savedPct: Math.round((1 - afterBytes / beforeBytes) * 100),
  };
}

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = await walk(ROOT);
const rows = [];
for (const f of files) {
  try {
    const r = await processFile(f);
    rows.push(r);
  } catch (err) {
    rows.push({ path: f, error: String(err) });
  }
}

console.table(
  rows.map((r) => ({
    file: r.path.replace(ROOT + "/", ""),
    ...(r.skipped ? { skipped: r.skipped } : {}),
    ...(r.error ? { error: r.error } : {}),
    ...(r.beforeKB !== undefined ? { beforeKB: r.beforeKB, afterKB: r.afterKB, savedPct: r.savedPct } : {}),
  }))
);

// Write manifest
const manifestBody = `// AUTO-GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
// Re-run: node scripts/optimize-images.mjs
//
// Maps /images/* public paths to base64 JPEG data URLs (~16px wide).
// Consumed by <Image placeholder="blur" blurDataURL={imageBlur[src]} />.

export const imageBlur: Record<string, string> = ${JSON.stringify(blurManifest, null, 2)};
`;
await writeFile("src/data/imageBlur.ts", manifestBody);
console.log(`\nWrote ${Object.keys(blurManifest).length} blur entries to src/data/imageBlur.ts`);
